### ISSUE TITLE
We never cover the %w array creator, yet we use it in the tests

### ISSUE THREAD

**Issue by jmburges** [learn-co-curriculum/cartoon-collections#11]
https://github.com/learn-co-curriculum/cartoon-collections/blob/master/spec/cartoon_collections_spec.rb#L22

Just use the regular array creator

**Comment by jmburges** [comment]
also here https://github.com/learn-co-curriculum/cartoon-collections/blob/master/spec/cartoon_collections_spec.rb#L29

and a few other places

**Comment by danny-sullivan** [comment]
Updated.
