### ISSUE TITLE
SHouldn't have two of the same expect stuf fin one if block

### ISSUE THREAD

**Issue by jmburges** [learn-co-curriculum/cartoon-collections#12]
https://github.com/learn-co-curriculum/cartoon-collections/blob/565cfb6164fa7c9f6181dfbde496d491d0dff638/spec/cartoon_collections_spec.rb#L33-L35

That is doing another test...yet it's in the same it block. Should be two it blocks. Technically, we shouldn't just test the same method with two different inputs, but this blocks the just making it work for one input problem

**Comment by danny-sullivan** [comment]
Updated.
