### ISSUE TITLE
Testing two distinct things in one if

### ISSUE THREAD

**Issue by jmburges** [learn-co-curriculum/cartoon-collections#13]
Here https://github.com/learn-co-curriculum/cartoon-collections/blob/565cfb6164fa7c9f6181dfbde496d491d0dff638/spec/cartoon_collections_spec.rb#L44-L45 we are testing the true and the false case.

Those belong in two different tests. In general you only want one expect per it anyways

**Comment by danny-sullivan** [comment]
Updated.
