### ISSUE TITLE
More separation of expects into their own it blocks

### ISSUE THREAD

**Issue by jmburges** [learn-co-curriculum/cartoon-collections#14]
notice how each of these https://github.com/learn-co-curriculum/cartoon-collections/blob/565cfb6164fa7c9f6181dfbde496d491d0dff638/spec/cartoon_collections_spec.rb#L51-L61 is a logical separate thing? Make it actually a logical separate thing! many it blocks

**Comment by danny-sullivan** [comment]
Updated.
