### ISSUE TITLE
Mistake in .rspec file

### ISSUE THREAD

**Issue by JVThomas** [learn-co-curriculum/cartoon-collections#16]
describe "#long_planteer_calls" do
    it "returns true if any calls are longer than 4 characters" do
      long_planteer_calls = ["earth", "wind", "fire", "water", "heart"]   -->  variable is long_planteer_calls
      expect(long_planteer_calls(long_planeteer_calls)).to eq(true) -->  variable is long_planeteer_calls
    end

Misspelled variable causes test to fail due to undefined variable no matter what.

Segment can be found in lines 41-45 of cartoon_collections_spec.rb

**Comment by AnnJohn** [comment]
thanks! we updated the tests.
