### ISSUE TITLE
Typo in spec file

### ISSUE THREAD

**Issue by kvignali** [learn-co-curriculum/cartoon-collections#17]
In the Cartoon_collections_spec.rb file there was a typo i believe the word plan(e)teer was spelled wrong: I fixed it like this: describe "#long_planteer_calls" do it "returns true if any calls are longer than 4 characters" do long_planeteer_calls = ["earth", "wind", "fire", "water", "heart"] expect(long_planeteer_calls(long_planeteer_calls)).to eq(true) end it "returns false if all calls are shorter than 4 characters" do short_planeteer_calls = ["wind", "fire"] expect(long_planeteer_calls(short_planeteer_calls)).to eq(false) end

**Comment by AnnJohn** [comment]
Fixed

**Comment by dsstewa** [comment]
it "returns false if all calls are shorter than 4 characters" do
    calls_short = ["wind", "fire"]
    expect(long_planeteer_calls(calls_short)).to eq(false)
    end

This should read "returns false if all calls are 4 characters or less"
