### ISSUE TITLE
Wrong test suite

### ISSUE THREAD

**Issue by buckethead1986** [learn-co-curriculum/cartoon-collections#23]
The test suite tests for things not part of the code given. (This is a lab where all the code is handed to us to input, but the test suite is testing for different things).

Here is the code given to us:
`def hello_t(array)
  i = 0

  while i < array.length
    yield(array[i])
    i = i + 1
  end

  array
end

hello_t(["Tim", "Tom", "Jim"]) do |name|
  if name.start_with?("T")
    puts "Hi, #{name}"
  end
end`

And here is the test suite:
`require "spec_helper"

describe "#hello_t" do
  let (:names) { ["Tim", "Tom", "Jim"] }
  it "only passes names that start with 'T' to the block" do
    expect{hello_t(names){|name| puts "Hi, #{name}" }}.to output("Hi, Tim\nHi, Tom\n").to_stdout
  end

  it "returns an array with only names that start with 'T'" do
    expect(hello_t(names) {|name| puts "Hi, #{name}" }).to eq(["Tim", "Tom"])
  end

  it "is case insensitive" do
    other_names = ["tim", "tom", "jim"]
    expect{hello_t(other_names){|name| puts "Hi, #{name}" }}.to output("Hi, tim\nHi, tom\n").to_stdout
  end
end`

What it's supposed to do is iterate through the array, puts 'Hi, Tim' and 'Hi, Tom', and return the original array. The test suite wants other things, and an updated array returned.

**Comment by Tolenno** [comment]
I think that was a previous lab? This is one uses cartoon characters and requires you to use different iteration methods to complete the lab.

**Comment by sgharms** [comment]
Agree with you @mjhough. I think this is close-able.
