### ISSUE TITLE
clarify instructions

### ISSUE THREAD

**Issue by ShawnCodes** [learn-co-curriculum/cartoon-collections#29]
Readme instructions ask to "It should then **capitalize each element and add an exclamation point at the end.** " whereas the test specs expect only the first letter of each word to be capitalized ie. .capitalize instead of .upcase

**Comment by curiositypaths** [comment]
Hi there,

Thank you for bringing this to our attention. We double checked the README instructions (*It should then capitalize each element and add an exclamation point at the end.*), the example output ( ["Earth!", "Wind!", "Fire!", "Water!", "Heart!"]) and the specs. They all seem to be to correct assuming `capitalize each element` is interpreted as capitalizing only the first letter.

As always thank you for contributing.
