### ISSUE TITLE
lab says that it wasn't forked

### ISSUE THREAD

**Issue by hmalik88** [learn-co-curriculum/cartoon-collections#30]
lab says that it wasn't forked, however, i completed the lab, passed the tests and submitted pull request.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @hmalik88.

We have updated the materials and believe your issue to have been resolved for future students. It should be possible to get learn.co to register that you have completed the lab by deleting your personal fork of the lesson and reforking the lab.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
