### ISSUE TITLE
Specs for #long_planeteer_calls cause false pass

### ISSUE THREAD

**Issue by AspenJames** [learn-co-curriculum/cartoon-collections#31]
# Insufficient solution causes spec to pass

## The spec

```ruby
describe "#long_planeteer_calls" do
    it "returns true if any calls are longer than 4 characters" do
      calls_long = ["axe", "earth", "wind", "fire", "water", "heart"]
      expect(long_planeteer_calls(calls_long)).to eq(true)
    end

    it "returns false if all calls are shorter than 4 characters" do
    calls_short = ["wind", "fire"]
    expect(long_planeteer_calls(calls_short)).to eq(false)
    end

  end
```

## False positive "Solution"

Students' first intuition may lead them to experiment with `.length` without first turning to iteration. Below is one of the possible solutions a student may attempt:
```ruby
def long_planeteer_calls(words)
  if words.length > 4
    true
  else
    false
  end
end
```

Or even simply: 

```ruby
def long_planeteer_calls(words)
  words.length > 4
end
```

## Explanation

Calling the `#length` method on the argument array returns the length of the array. Unfortunately, the way the spec is written causes this to pass the specs, since the only example that is expecting `true` has six elements in the array, and the only example expecting `false` has only two elements  in the array. 

## Proposed solution

Simply removing two words from the argument given in the first spec and adding three or more words of length <= 4 to the second spec will fix this error, eliminating the possibility that a student could be passing spec with an insufficient solution. 

#Staff

**Comment by maxwellbenton** [comment]
Thank you for the detailed explanation, @AspenJames!

I've merged your PR in and tested it out. Thank you for contributing!
