### ISSUE TITLE
rspec test typo

### ISSUE THREAD

**Issue by dsstewa** [learn-co-curriculum/cartoon-collections#34]
it "returns false if all calls are shorter than 4 characters" do
calls_short = ["wind", "fire"]
expect(long_planeteer_calls(calls_short)).to eq(false)
end

This should read "returns false if all calls are 4 characters or less"

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials to resolve this issue. Thanks for contributing!
