### ISSUE TITLE
Solved This Lab with Incorrect Logic For #long_planeteer_calls and #find_the_cheese

### ISSUE THREAD

**Issue by fbohz** [learn-co-curriculum/cartoon-collections#35]
Hey guys. I got to pass this test passing with an incorrect logic so seems the rspec didn't meet all criteria. I realized it afterward and managed to go back to fix my code and solve it.  

Just wanted to report on it. Here's the incorrect logic that passed it:

```
#logic is not correct and I passed.
 def long_planeteer_calls(arr)
  arr.find do |x|
  if x.length == 4
   return false
  else
   return true
  end
  end
end   

#incorrect logic and it passed.
def find_the_cheese(arr)
  # the array below is here to help
  cheese_types = ["cheddar", "gouda", "camembert"]
  counter = 0
  arr.find do |x|
  if x == cheese_types[counter]
  x
  else
  nil
end
end
end
```

**Comment by drakeltheryuujin** [comment]
Thank you for your feedback! Your logic isn't entirely "wrong", however they don't follow the instructions. We'll take this information into consideration in upcoming releases of this curriculum.

Thanks for contributing! 💙

**Comment by fbohz** [comment]
Ok great got it :)
